services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"